# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
stripe_api_key: sk_test_RE93dXx7wPZhAU41Of56vnp4
stripe_publishable_key: pk_test_o3AtpVVVTUpb8zqsIh4bBdvc
#
# production:
stripe_api_key: sk_test_RE93dXx7wPZhAU41Of56vnp4
stripe_publishable_key: pk_test_o3AtpVVVTUpb8zqsIh4bBdvc
